export enum MyCollectionSortType {
  TITLE_ASC = "TITLE_ASC",
  TITLE_DESC = "TITLE_DESC",
  YEAR_ASC = "YEAR_ASC",
  YEAR_DESC = "YEAR_DESC",
  RATING_ASC = "RATING_ASC",
  RATING_DESC = "RATING_DESC",
  STATUS_ASC = "STATUS_ASC",
  STATUS_DESC = "STATUS_DESC",
  ADDED_ASC = "ADDED_ASC",
  ADDED_DESC = "ADDED_DESC",
}

export enum CompleteStatus {
  COMPLETE = "COMPLETE",
  INCOMPLETE = "INCOMPLETE",
  ALL = "ALL",
}
